# Generated by Django 3.1.1 on 2020-10-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('opt_1', models.CharField(max_length=200)),
                ('opt_2', models.CharField(max_length=200)),
                ('opt_3', models.CharField(max_length=200)),
                ('opt_4', models.CharField(max_length=200)),
                ('correct', models.CharField(max_length=200)),
                ('hint', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
